pipeline {
    agent any
    parameters {
        booleanParam(name: "RELEASE", defaultValue: "false", description: "Check this option only if its a release")
    }
    tools {
        go 'go-1.15.2'
    }
    stages {
        stage('Check versions'){
            steps {
                script {
                    auditTools()
                }
            }
        }
        stage('Unit tests'){
            steps {
                sh 'pwd'
                sh 'ls -al'
                sh 'go test ./internal/...'
            }
        }
    }
    post {
        success {
            echo "Successful build"
        }
        failure {
            echo "Failure"
        }
    }
}

String auditTools(){
    sh '''
        go version
        git --version
    '''
}