pipeline {
    agent any
    input {
        parameters{
            string(name: "ENVIRONMENT", defaultValue: "development", description: "The environment that the app runs")
        }
    }

    stages{
        stage("Audit tools"){
            steps {
                sh '''
                    git version
                    go version
                '''
            }
        }
        stage("Unit tests"){
            dir('./server'){
                steps {
                    sh '''
                    go test -v ./...
                    '''
                }
            }
        }
        stage("Build app"){
            dir("./server"){
                steps {
                    sh '''
                        go build -o ./bin/server ./cmd/server/main.go
                    '''
                }
            }
        }
        stage("Deploy"){
            steps {
                echo "Do deployment"
            }
        }
    }
    post {
        success {
            slackSend(color: "good", channel: "#jenkins", message: "Successful build")
        }
        failure {
            slackSend(color: "danger", channel: "#jenkins", message: "Failed build")
        }
    }
}