pipeline {
    agent any
    parameters{
        string(name: "ENVIRONMENT", defaultValue: "development", description: "The environment that the app runs")
    }
    script {
        def root = tool name: 'Go 1.12', type: 'go'
    }

    stages{
        stage("Audit tools"){
            steps {
                sh '''
                    git version
                    go version
                '''
            }
        }
        stage("Unit tests"){
            steps {
                sh "go test -v ./..."
            }
        }
        stage("Build app"){
            steps {
                sh "go build -o ./bin/server ./cmd/server/main.go"
            }
        }
        stage("Deploy"){
            steps {
                echo "Do deployment"
            }
        }
    }
    post {
        success {
            slackSend(color: "good", channel: "#jenkins", message: "Successful build")
        }
        failure {
            slackSend(color: "danger", channel: "#jenkins", message: "Failed build")
        }
    }
}