pipeline {
    agent any
    parameters {
        booleanParam(name: "RELEASE", defaultValue: false, description: "Check this option only if its a release")
    }
    tools {
        go 'go-1.15.2'
    }
    stages {
        stage('Check versions'){
            steps {
                script {
                    def utils = load("scripts/3.2/Utils.groovy")
                    utils.auditTools()
                }
            }
        }
        stage('Unit tests'){
            steps {
                sh 'go test ./scripts/3.1/internal/...'
            }
        }
        stage('Generates binary and release it'){
            when {
                expression {
                    return params.RELEASE
                }
            }
            steps {
                sh '''
                    go build -o ./scripts/3.1/bin/server ./scripts/3.1/cmd/server/main.go 
                '''
            }
        }
    }
    post {
        success {
            echo "Successful build"
        }
        failure {
            echo "Failure"
        }
    }
}